
*Entwurf und Implementierung der Request-Verarbeitungskette unter Verwendung des Model-View-Presenter Architekturmusters.*

[discrete]
==== Ausgangssituation

Im Prototyp war die Code der Benutzerobeflächengenerierung stark mit der Code der Anwendungslogik vermischt.
Es hat ausgereicht um die gewünschte Funktionalität der Anwendung bereitzustellen. Aber das hat die Zusammenarbeit an der Code mit den anderen Teammitglieder stark verhindert.
Die Störfaktoren waren unter anderem:

- Große Anstrengung für jeden Teammitglied beim Einstieg in die Programmierarbeit, weil jeder sich mit der kompletten Anwendungslogik auseinandersetzen musste.
- Viele potenzielle Konflikte im Git, da die zuerfüllende Aufgaben mehrerer Programmierer sich oft auf die gleiche Quelltext-Datei bezogen.
- Situationen, wenn ein Entwickler auf die Arbeit eines Anderen warten muss , bevor er eigene Aufgaben erledigen konnte.
- Eventuelle zukünftige Verwendung eines alternativen Datenbankmanagementsystems wäre mit zu großen Änderungen verbunden.

[discrete]
==== Lösungsweg
Um die Schwierigkeiten zu adressieren haben wir im Team entschieden eine saubere "Separation of Concerns" durchzusetzen. Den MVP-Architekturmuster fand ich dafür am besten geeignet.

[discrete]
===== View-Presenter-Verbindung
Die Daten, die durch eine View-Komponente dem Nutzer angezeigt werden sollen, waren großenteils noch aus der Analyse-Phase des Projekts bekannt.
Für jede View-Komponente musste eine Klasse für die anzuzeigende Daten entworfen werden. Die Daten-Klasse diente dann als Schnittstelle zwichen der Controller-Komponente und dem View.

Somit waren für jede durch den Nutzer aufgerufene Ansicht drei Klassen notwendig: die View-Klasse, wo der endgültige HTML-Response erstellt wird, die Controller-Klasse, die die Daten für das View bereitstellt und die Datenschnittstellen-Klasse selbst.

Als erstes habe ich View-, Controller- und Datenschnittstellen-Basisklasse implementiert. In den Basisklassen waren die Initialisierungsvorgänge und andere für alle Kindklassen notwendige Prozeduren versteckt. Damit habe ich erreicht, dass zum Beispiel ein Entwickler, der für eine bestimmte View-Komponente zuständig ist, sich fast ausschließlich mit dem Rendern der HTML-Ausgabe beschäftigen kann.

Die von der Datenschnittstellen-Basisklasse geerbte Datenschnittstellen-Klasse konnte sowohl der View-Entwickler als auch der Cotroller-Entwickler anlegen. Damit war die Abhängigkeit der beiden Entwickler voneinander abgekoppelt und sie mussten nicht aufeinander warten.

[discrete]
====== Nutzeraktionen
Eine besondere Herausforderung war einen Weg zu finden, wie die View-Komponente die Benutzereingabemöglichkeiten in den HTML-Response integriert. Dafür habe ich Nutzeraktion-Klasse eingeführt. Controller übergab der View-Komponente Instanzen dieser Nutzeraktion-Klasse und View-Komponente konnte die Nutzeraktion-Instanzen auf die HTML-Benutzereigabemöglichkeiten (Hyperlinks, Eingabefelder, Buttons, ...) abbilden.

[discrete]
===== Modell
Die für die Anwendung erforderliche Datenstrukturen wurden im Prototyp im Programm-Speicher verwaltet. Es gab Bedenken, dass die Leistung der InMemory-Datenverwaltung irgendwann nicht mehr ausreicht und deswegen ein externes Datenbanksystems (z.B SQLite) notwendig wird.
Der Austausch des Datenverwaltungmoduls ist nur möglich, wenn die Datenabfragen und Datenmanipulationen in der Anwendung über eine genau definierte Schnittstelle durchgeführt werden. Die Datenbankschnittstelle habe ich als eine abstrakte Klasse realisiert. In der abstrakten Klasse sind die Funktionen nur deklariert und die Klassen der Datenstrukturen definiert. Konkrete Implementierung der Funktionen findet in den von der abstrakten Klasse abgeleiteten Datenbank-Backend-Klassen statt.

[discrete]
===== Documentation
Um den anderen Teammitglieder die Anwendungsstruktur zu erklären habe ich eine graphische Skizze des Requestsablaufs erstellt. Für einige Views habe ich die View-, Datenschnittstelle- und Controller-Klassen komplett implementiert, damit sie als Beispiel bei der Erstellung weiterer Klassen dienen. In jeder Datenschnittstellenklasse habe ich Platzhalterdaten definiert, damit die View-Entwickler die Beispiele bei noch nicht abgeschlossener Datenbankimplementierung nachvollziehen können.

[discrete]
==== Bewertung
Das Vorhaben ist meiner Meinung nach gelungen. Großer Teil der User-Stories kann mit der Requestverarbeitungskette realisiert werden. Auf die implementierte Struktur kann man sich verlassen. Die Arbeitsschritte für die Benutzung des Systems durch einen neuen Entwickler sind erlernbar. Aufgaben für die Entwickler können damit genau definiert und in einer vorhersehbaren Zeit erledigt werden.

In unserem Team war sowohl ein Entwickler, der von Anfang an da war als auch jemand, der später dazugekommen ist. Sie beide konnten sich gut in das Requestbearbeitungsprozess einarbeiten.

Aber es gibt noch ein Verbesserungsbedarf, der im Zeitrahmen des SE-Projekts nicht realisierbar war. Einige Schritte beim Anlegen der Requestverarbeitungskette für eine neue View sind zu umständig und müssen optimiert werden. Einstieg eines neuen Entwicklers dauert noch zu lange und die Ursache dafür ist noch nicht ganz klar. Das könnte zum Beispiel an nicht intuitiven Schritten im Gesamtvorgehen liegen oder vielleicht an der nicht ausreichender Dokumentation.

Eine positive Entdeckung möchte ich noch erwähnen: in der Testphase ließen sich die Unit-Tests für die umgesetzte Struktur gut definieren.



