@startuml
!include C4_Context.puml

title C4-Context

Person(organisator, "Organisatoren des Turniers", "Die für die Planung, den Ablauf und die Auswertung des Turniers verantwortliche Personen.")
Person(spieler, "Spieler", "Teilnehmer eines Teams.")

System(turnierauswertungssoftware, "HTWD Turnierauswertungssoftware", "Automatisiert die Plannung, Erfassung und Auswertung eines Volleyball-Turniers.")

Rel_D(organisator, turnierauswertungssoftware, "Uses")
Rel_D(spieler, turnierauswertungssoftware, "Uses")

@enduml
