@startuml
!include C4_Context.puml
!include C4_Container.puml

title C4-Container

Person(organisator, "Organisatoren")
Person(spieler, "Spieler")



System_Boundary(turnierauswertungssoftware, "HTWD Turnierauswertungssoftware", "Automatisiert die Plannung, Erfassung und Auswertung eines Volleyball-Turniers."){
  Container(web_app, "Web-Anwendung","Java")
  Container(database, "Datenbank")
}

Rel_D(organisator, web_app, "Uses", "HTTP")
Rel_D(spieler, web_app, "Uses", "HTTP")
Rel_D(web_app, database, "Reads from and\n writes to")

@enduml
