@startuml Use-Case-Diagram

:Organisator: -u-> (Archiviert das Turnier.\nLädt einen Turnier aus dem Archiv)
:Organisator: -r-> (Nutzt die Software um die Turnierdaten\nzu generieren, abfragen\nund zu ändern)
:Spieler: -l-> (Nutzt die Software um die Turnierdaten\nzu generieren, abfragen\nund zu ändern)
:Organisator: -d-> (Möchte in der Zukunft\ngrößere Turniere organisieren)
:Organisator: -d-> (Benutzt das System\nbei fehlender\nInternetverbindung)
:Spieler: -d-> (Benutzt das System\nbei fehlender\nInternetverbindung)
:Spieler: -u-> (Benutzt das System\nüber mobile Endgeräte)


@enduml
