= System-Wide Requirements: {project-name}
;
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt <Thema> spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. [hier ggf. Verweis einfügen]


== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz
* Druckbarkeit von Spielplan und Turnier-Auswertung
* optional: Authentifizierung von Spielern -> ermöglicht Auditing von Spielstandsänderungen
* Behandlung von gleichzeitigen Änderungsanfragen
* Logging von Fehlern

== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)
* Die Spieler müssen intuitiv die Verwendung der Software verstehen ohne bei der Organisation nachzufragen
* Das Eintragen der Spielstände darf nicht länger als 30 Sekunden dauern.
* Die Spieler sollen durch die Software ein besseres Turniererlebnis als ohne haben.
* Das Öffnen der Softwareumgebung muss innerhalb von 15 Sekunden (z.B. über einen QR-Code) möglich sein.

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.
* Die Berechnungen des Systems müssen determiniert sein.
* Fehlerhafte Nutzereingaben müssen korrigiert werden können.
* Das System stellt keine hohen Ansprüche an die Verfügbarkeit, da es nicht kritisch ist.
* Die Spielstände sollten wiederherstellbar sein, wenn diese durch technische Fehler oder Fehlverhalten der Nutzer verloren gehen.

=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.
* Es müssen mindestens 200 Nutzer gleichzeitig auf die Software zugreifen können.
* Es sollten mehrere Eingaben von Nutzern in nicht-spürbarer Zeit verarbeitet werden können.

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.
* Der Quellcode sollte strukturiert und kommentiert sein, um spätere Erweiterungen zu ermöglichen.
* Das System muss nicht stark skalierbar sein und es sind keine großen Funktionalitätserweiterungen im Nachhinein vorgesehen.

== Zusätzliche Anforderungen

=== Technische Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
//* Ressourcenbegrenzungen:
//* zu nutzende Komponenten / Bibliotheken / Frameworks
//* Vorgaben für die Programmiersprache
* zu unterstützende Plattformen / Betriebssysteme: alle aktuellen Desktop- und mobilen Betriebssysteme (Windows, MacOS, Linux, iOS, Android) mit aktuellen Browsern (Chrome, Safari, Edge, Firefox, Opera etc.)
* Physische Begrenzungen für Hardware, auf der das System betrieben werden soll: muss auf leistungsschwachem Laptop funktionieren

=== Interface Anforderungen
// Describe both the user interface and interfaces with external systems.
Die Benutzeroberfläche sollte zeitlos gestaltet sein und alle wichtigen Funktionalitäten sollten ohne langes Scrollen zur Verfügung stehen. Eine intuitive Bedienbarkeit für Menschen mit technischem Grundverständnis soll sichergestellt werden.

=== Geschäftsregeln
// Besides technical requirements, also consider the particular business domain in which the system needs to fit.
Derzeit sind keine relevanten Geschäftsregeln bekannt.

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Anforderungen an Betrieb, Management und Wartung der Anwendung: Die Software wird nicht dauerhaft benötigt sondern nur akut im Planungs- und Austragungszeitraum von Turnieren benutzt.
//* zu beachtende Standards, Normen und Regeln

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
//* Lizensierung der Anwendung
* Datenschutz: Es muss die Datenschutz-Grundverordnung eingehalten werden.
