services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-storage-dev:/var/lib/postgresql/data

volumes:
  postgres-storage-dev: {}

