services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    network_mode: "host"
  database:
    image: postgres:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-storage-dev:/var/lib/postgresql/data

volumes:
  postgres-storage-dev: {}

