services:
  caddy:
    container_name: turnier-caddy
    image: caddy
    restart: unless-stopped
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
  website:
    container_name: turnier-website
    image: node:lts-alpine
    restart: unless-stopped
    working_dir: /home/node/app
    volumes:
      - ./website:/home/node/app
    command: "npm run devexp"
  api:
    container_name: turnier-api
    build: ./api
    restart: unless-stopped
    develop:
      watch:
        - path: ./api
          action: rebuild

  database:
    container_name: turnier-database
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - turnier-postgres-storage-dev:/var/lib/postgresql/data

volumes:
  turnier-postgres-storage-dev: {}

