services:
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-storage:/var/lib/postgresql/data
  website:
    restart: unless-stopped
    build: ./website
    ports:
      - "80:3000"
  api:
    restart: unless-stopped
    build: ./api
    ports:
      - "8080:8080"

volumes:
  postgres-storage: {}

