services:
  caddy:
    container_name: turnier-caddy
    image: caddy
    restart: unless-stopped
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-storage:/var/lib/postgresql/data
  website:
    restart: unless-stopped
    build: ./website
  api:
    restart: unless-stopped
    build: ./api

volumes:
  postgres-storage: {}

