@startuml Domain Model
skinparam linetype ortho
skinparam nodesep 140

object Turnier
object Organisator
object Auswertung
object Turnierplan
  Turnierplan : + Bedingungen
object Match
  Match : + Spielstand
  Match : \n
object Team
  Team : + Name
  Team : \n
  
object Leistungsgruppe
object Spielfeld

Auswertung "0..1" -r- "1" Turnier
Turnier "1..*" -r- "1" Organisator
Turnier "1" -d- "1" Turnierplan
Turnierplan "1" *-d- "3..*" Match
Leistungsgruppe "1" *-- "3..*" Team


Leistungsgruppe "1" -- "3..*" Match
Team "1" -r- "2..*" Match : Team 1
Team "1" -r- "2..*" Match : Team 2
Team "1" -r- "0..*" Match : Richter

Match "0..*" -r- "1" Spielfeld

@enduml